version: "3"

services:
  ### GUI KAFKA TOOLS
  akhq:
    image: tchiotludo/akhq
    ports:
      - 8080:8080
    volumes:
      - ./akhq/application.yml:/app/application.yml
    links:
      - kafka

  ### MAIN SERVICES
  zookeeper:
    image: zookeeper:latest
    restart: always
    ports:
      - 2181:2181
  # environment:
  # ZOO_MY_ID: 1
  # ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    expose:
      - 9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ### SEPARATE INTERFACE FOR SECURITY
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      # KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

      ### NON-SEPARATE INTERFACE
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.150.28.64:9092 ## HOST-MACHINE IP
      KAFKA_LISTENERS: PLAINTEXT://:9092

  connect:
    build: ./connect
    depends_on:
      - elastic
      - mysql
      - mongodb
    links:
      - mysql
      - kafka
      - zookeeper
    ports:
      - 8083:8083
    volumes:
      - ./connect/data/connect:/kafka/connect:rw
    environment:
      BOOTSTRAP_SERVERS: kafka:9093
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KAFKA_CONNECT_PLUGINS_DIR: /kafka/connect,/kafka/plugins

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    depends_on:
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9093
      # SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  #### DATABASES SECTION
  mysql:
    image: mysql:5.7
    ports:
      - 6603:3306
    volumes:
      - ./mysql-conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysqlpw

  elastic:
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 8881:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  #### DATABASE TOOLS
  kibana:
    image: kibana:7.6.2
    ports:
      - 5601:5601
    depends_on:
      - elastic
    links:
      - elastic
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200

  mongodb-express:
    image: mongo-express:latest
    ports:
      - 28881:8081
    links:
      - mongodb:mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_MONGODB_URL: "mongodb://root:root@mongodb:27017?ssl=false"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "root"
      ME_CONFIG_OPTIONS_EDITORTHEME: "lesser-dark"
